projects:
  Codegen Project:
    schemaPath: ../../graphql/schema.json
    includes:
      - ./queries.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: ./API.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: null
        frontend: javascript
        framework: react-native
extensions:
  amplify:
    version: 3
